

name: Try

on:
  workflow_dispatch: 
  push:    # 当对分支master进行push操作的时候，这个工作流就被触发了
     branches: [ main ]
  schedule:
    - cron: 0 0 * * *
jobs:
  try_job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
    - name: requirements
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt      
    - uses: actions/checkout@v2
#     - name: Run Try.py
#       run: python sendmail.py
    - name: Save Dataframe to CSV
      run: python -c "import pandas as pd; df = pd.read_csv('dataframe.csv'); df.to_csv('dist/dataframe.csv', index=False)"
    - name: Trigger next job
      uses: actions/github-script@v2
      with:
        script: |
          const jobName = 'second_try_job';
          const myToken = core.getInput('repo-token');
          const octokit = new github.GitHub(myToken);
          await octokit.actions.createWorkflowDispatch({
            owner: github.context.repo.owner,
            repo: github.context.repo.repo,
            workflow_id: jobName
          });
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  second_try_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
    - name: requirements
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt      
    - uses: actions/checkout@v2
    - name: Read Dataframe from CSV
      run: python -c "import pandas as pd; df = pd.read_csv('dist/dataframe.csv')"
#     - name: Run Try.py
#       run: python send2.py
    - name: Save Dataframe to CSV
      run: python -c "import pandas as pd; df = pd.read_csv('dataframe.csv'); df.to_csv('dist/dataframe.csv', index=False)"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
