#工作名字
name: new formal正式流程
#
on:
  workflow_dispatch: 
  push:
  # 当对分支master进行push操作的时候，这个工作流就被触发了
    branches: [ main ]
  pull_request:
  #只运行特定分支master
    branches: [ main ]
  schedule:
  # 定时任务，在每天的24点 18点推送签到信息到邮箱
    - cron:  10 19 * * 0 
      # 定时器更改时间
      # https://tool.lu/crontab/
      # https://datetime360.com/cn/utc-cst-china-time/ #UTC时间 国际协调时间+8=北京时间
      # https://docs.github.com/cn/actions/using-workflows/workflow-syntax-for-github-actions#onschedule 官方参考
  #watch:
  #    types: started   

jobs:
#将工作流程中运行的所有作业组合在一起
  checkin:
  #定义名为 checkin 的job。 子键将定义作业的属性 
    runs-on: windows-latest    #将作业配置为在最新版本的 windows运行器上运行
    steps:
    - uses: actions/checkout@v2
#uses 关键字指定此步骤将运行 actions/checkout 操作的 v2。 这是一个将存储
#库签出到运行器上的操作，允许您对代码（如生成和测试工具）运行脚本或其他操
#作。 每当工作流程将针对存储库的代码运行时，都应使用签出操作。
      with:
        COOKIE1: ${{ secrets.COOKIE1 }}
        FREQ: ${{secrets.FREQ}}
        ENCODE: ${{secrets.ENCODE}}
        URL: ${{secrets.URL}}

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
    - name: requirements
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt      
    - name: Checkin
      run: |
        python3 ./boc.py
      
      
      
      

      env:   
      #设置secrets的环境变量
        COOKIE1: ${{ secrets.COOKIE1 }}
        FREQ: ${{secrets.FREQ}}
        ENCODE: ${{secrets.ENCODE}}
        URL: ${{secrets.URL}}
