#工作名字
name: 串联尝试.yml
#
on:
  workflow_dispatch: 
  push:    # 当对分支master进行push操作的时候，这个工作流就被触发了
     branches: [ main ]
#  pull_request:  #只运行特定分支master
#    branches: [ main ]
  schedule:  # 定时任务，在每天的24点 18点推送签到信息到邮箱
    - cron:  10 19 * * 0 
   

jobs:
#将工作流程中运行的所有作业组合在一起

  checkin:  #定义名为 checkin 的job。 子键将定义作业的属性 
    runs-on: windows-latest    #将作业配置为在最新版本的 windows运行器上运行
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
    - name: requirements
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt      
    - name: Checkin
      run: |
        python3 ./sendmail.py
      env:   
      #设置secrets的环境变量
        COOKIE1: ${{ secrets.COOKIE1 }}
        FREQ: ${{secrets.FREQ}}
        ENCODE: ${{secrets.ENCODE}}
        URL: ${{secrets.URL}}

  checkin1:  #定义名为 checkin 的job。 子键将定义作业的属性 
    runs-on: windows-latest    #将作业配置为在最新版本的 windows运行器上运行
    needs: checkin
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
    - name: requirements
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt      
    - name: Checkin1
      run: |
        python3 ./sendmail.py
      env:   
      #设置secrets的环境变量
        COOKIE1: ${{ secrets.COOKIE1 }}
        FREQ: ${{secrets.FREQ}}
        ENCODE: ${{secrets.ENCODE}}
        URL: ${{secrets.URL}}
